import sys; sys.path.insert(0, r'C:\PUMPCALC')
from src.application.validated_calculator import run_validated
r = run_validated()
print('Validated Calculations:')
print('=' * 60)
print(f'Discharge diameter: {r["discharge_diameter_in"]:.4f} in')
print(f'Suction diameter: {r["suction_diameter_in"]:.4f} in')
print()
print(f'Re discharge: {r["re_discharge"]:.0f}')
print(f'Re suction: {r["re_suction"]:.0f}')
print()
print(f'f discharge (Colebrook): {r["f_discharge"]:.6f}')
print(f'f suction (Colebrook): {r["f_suction"]:.6f}')
print()
print(f'hf/ft discharge: {r["hf_per_ft_discharge"]:.6f} ft/ft')
print(f'hf/ft suction: {r["hf_per_ft_suction"]:.6f} ft/ft')
print()
print(f'NPSHa: {r["npsha_ft"]:.2f} ft')
print()
print(f'TDH: {r["tdh_ft"]:.2f} ft')
print()
print(f'Shaft HP: {r["shaft_hp"]:.2f}')
print(f'Shaft kW: {r["shaft_kw"]:.2f}')
print()
print(f'Specific speed (US): {r["specific_speed_us"]:.0f}')
print(f'Specific speed (Metric): {r["specific_speed_metric"]:.1f}')
print(f'Specific speed (Legacy): {r["specific_speed_legacy"]:.0f}')
print()
print('Friction Factor Comparison:')
for side, comp in r['friction_comparison'].items():
    print(f'  {side}: Re={comp["Re"]}, legacy_f={comp["legacy_f"]:.6f}, validated_f={comp["validated_f"]:.6f}, diff={comp["difference_pct"]:.0f}%')